# Streamlit Community Cloud Secrets Configuration
# Copy this file to your Streamlit Cloud app settings > Secrets section
# Replace all placeholder values with your actual credentials

# MongoDB Configuration
MONGO_URI = "mongodb+srv://username:password@cluster.mongodb.net/database_name?tls=true&authMechanism=SCRAM-SHA-256&retrywrites=false&maxIdleTimeMS=120000"

# Antler Hub Credentials (for scraping)
ANTLER_EMAIL = "your_email@example.com"
ANTLER_PASSWORD = "your_antler_password"

# OpenAI API Key (for founder classification)
OPENAI_API_KEY = "sk-proj-your_openai_api_key_here"

# Dashboard Password Protection
DASHBOARD_PASSWORD = "your_secure_dashboard_password"